
export type Product = {
  id: number
  images: string[]
  brand: string
  model: string
  price: number
  processorGeneration: string
  processor: string
  ram: string
  storage: string
  batteryHealth: string
  webcam: string
  bluetooth: string
  screenSize: string
  touchscreen: string
  keyboardLight: string
}

export const products: Product[] = [
  {
    id: 1,
    images: ["/images/Latitude-3550-13th-Gen.png", "/images/Latitude-3550-13-Gen-1.png"], 
    brand: "Dell",
    model: "2023 Latitude 3550",
    processor: "Intel Core i5",
    processorGeneration: "13th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 450000,
  },
  {
    id: 2,
    images: ["/images/latitude_7270_6th.png", "/images/latitude_7270.png"],
    brand: "Dell",
    model: "Latitude 7270",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 240000,
  },
  {
    id: 3,
    images: ["/images/thinkpad_x270_6th.png", "/images/thinkpad_x230_1.png"],
    brand: "Lenovo",
    model: "Thinkpad x270",
    processor: "Intel Core i5",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 250000,
  },
  {
    id: 4,
    images: ["/images/Eliebook-840-G7-1.png", "/images/Eliebook-840-G7.png"],
    brand: "HP",
    model: "Elitebook 840 G7",
    processor: "Intel Core i5",
    processorGeneration: "10th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "Yes",
    keyboardLight: "Yes",
    price: 400000,
  },
  {
    id: 5,
    images: ["/images/probook_440_G3.png", "/images/probook_440_G3_1.png", "/images/probook_440_G3_2.png"],
    brand: "HP",
    model: "Probook 440 G3",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "yes",
    keyboardLight: "Yes",
    price: 250000,
  },
  {
    id: 6,
    images: ["/images/Elitebook-840-G8-1.png", "/images/Elitebook-840-G8.png"],
    brand: "HP",
    model: "EliteBook 840 G8",
    processor: "Intel Core i5",
    processorGeneration: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 450000,
  },
  {
    id: 7,
    images: ["/images/Latitude-5480-1.png", "/images/Latitude-5480.png"],
    brand: "DELL",
    model: "Latitude 5480",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 33000,
  },
  {
    id: 8,
    images: ["/images/thinkpadL480_1.png", "/images/thinkpadL480.png"],
    brand: "Lenovo",
    model: "Thinkpad L480",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 9,
    images: ["/images/Elitebook-820-G3.png", "/images/Elitebook-820-G3-1.png"],
    brand: "HP",
    model: "Elitebook 820 G3",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "12 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 270000,
  },
  {
    id: 10,
    images: ["/images/latitude5400.png", "/images/latitude5400_1.png"],
    brand: "DELL",
    model: "Latitude 5400",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 290000,
  },
  {
    id: 11,
    images: ["/images/HP-250-G6.png", "/images/HP-250-G6-1.png"],
    brand: "HP",
    model: "HP 25 G6",
    processor: "Intel Core i5",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "128GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 200000,
  },
  {
    id: 12,
    images: ["/images/latitude3380.png", "/images/latitude3380_1.png"],
    brand: "DELL",
    model: "Latitude 3380",
    processor: "Intel Core i5",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "33.3 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 230000,
  },
  {
    id: 13,
    images: ["/images/Elitebook-745-G3-1.png", "/images/Elitebook-745-G3.png"],
    brand: "HP",
    model: "Elitebook 745 G3",
    processor: "Intel Core i5",
    processorGeneration: "AMD Processor",
    ram: "8GB",
    storage: "128GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "12.5 inches",
    touchscreen: "No",
    keyboardLight: "No",
    price: 200000,
  },
  {
    id: 14,
    images: ["/images/Latitude-7380.png", "/images/Latitude-7380-1.png"],
    brand: "DELL",
    model: "Latitude 7380",
    processor: "Intel Core i7",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "13.3 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 280000,
  },
  {
    id: 15,
    images: ["/images/Latitude-7250.png", "/images/Latitude-7250-1.png"],
    brand: "DELL",
    model: "Latitude 7250",
    processor: "Intel Core i5",
    processorGeneration: "5th Gen",
    ram: "8GB",
    storage: "128GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "12.5 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 200000,
  },
  {
    id: 16,
    images: ["/images/latitude5570.png", "/images/latitude5570_1.png"],
    brand: "DELL",
    model: "Latitude 5570",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15.6 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 17,
    images: ["/images/latitude3567.png", "/images/latitude3567_1.png"],
    brand: "DELL",
    model: "inspiron 15 3567",
    processor: "Intel Core i3",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "180GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15.6 inches",
    touchscreen: "Yes",
    keyboardLight: "Yes",
    price: 220000,
  },
  {
    id: 18,
    images: ["/images/latitude7270.png", "/images/latitude7270_1.png"],
    brand: "DELL",
    model: "Latitude 7270",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "12.5 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
]