
export type Product = {
  id: number
  images: string[]
  brand: string
  model: string
  price: number
  processorGeneration: string
  processor: string
  ram: string
  storage: string
  batteryHealth: string
  webcam: string
  bluetooth: string
  screenSize: string
  touchscreen: string
  keyboardLight: string
}

export const products: Product[] = [
  {
    id: 1,
    images: ["/images/latitude-3310.png", "/images/latitude-3310-2.png"],
    brand: "Dell",
    model: "Latitude 3310",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "13.3 inches",
    touchscreen: "Yes, 2in1, X360",
    keyboardLight: "Yes",
    price: 350000,
  },
  {
    id: 2,
    images: ["/images/latitude_7270_6th.png", "/images/latitude_7270.png"],
    brand: "Dell",
    model: "Latitude 7270",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 240000,
  },
  {
    id: 3,
    images: ["/images/thinkpad_x270_6th.png", "/images/thinkpad_x230_1.png"],
    brand: "Lenovo",
    model: "Thinkpad x270",
    processor: "Intel Core i5",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 250000,
  },
  {
    id: 4,
    images: ["/images/pavilion15.png", "/images/pavilion15_1.png"],
    brand: "HP",
    model: "Pavilion 15",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "500GB Hdd",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15.6 inches",
    touchscreen: "Yes",
    keyboardLight: "No",
    price: 260000,
  },
  {
    id: 5,
    images: ["/images/probook_440_G3.png", "/images/probook_440_G3_1.png", "/images/probook_440_G3_2.png"],
    brand: "HP",
    model: "Probook 440 G3",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "yes",
    keyboardLight: "Yes",
    price: 250000,
  },
  {
    id: 6,
    images: ["/images/840G3.png", "/images/840G3_1.png", "/images/440G3_2.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 7,
    images: ["/images/640G9_1.png", "/images/640G9.png"],
    brand: "HP",
    model: "EliteBook 640 G9",
    processor: "Intel Core i5",
    processorGeneration: "12th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 700000,
  },
  {
    id: 8,
    images: ["/images/thinkpadL480_1.png", "/images/thinkpadL480.png"],
    brand: "Lenovo",
    model: "Thinkpad L480",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 9,
    images: ["/images/lenovov110.png", "/images/lenovov110_1.png"],
    brand: "Lenovo",
    model: "V110 AMD",
    processor: "Intel Core i5",
    processorGeneration: "7th Gen",
    ram: "4GB",
    storage: "320GB Hdd",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15 inches",
    touchscreen: "No",
    keyboardLight: "No",
    price: 120000,
  },
  {
    id: 10,
    images: ["/images/latitude5400.png", "/images/latitude5400_1.png"],
    brand: "DELL",
    model: "Latitude 5400",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 290000,
  },
  {
    id: 11,
    images: ["/images/latitude3450_1.png", "/images/latitude3450.png"],
    brand: "DELL",
    model: "Latitude 3450",
    processor: "Intel Core i3",
    processorGeneration: "4th Gen",
    ram: "8GB",
    storage: "500GB Hdd",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 210000,
  },
  {
    id: 12,
    images: ["/images/latitude3380.png", "/images/latitude3380_1.png"],
    brand: "DELL",
    model: "Latitude 3380",
    processor: "Intel Core i5",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "33.3 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 230000,
  },
  {
    id: 13,
    images: ["/images/thinkpad-T480-1.png", "/images/thinkpad-T480-2.png"],
    brand: "Lenovo",
    model: "Thinkpad T480",
    processor: "Intel Core i7",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 300000,
  },
  {
    id: 14,
    images: ["/images/430G8.png", "/images/430G8_1.png"],
    brand: "HP",
    model: "EliteBook 430 G8",
    processor: "Intel Core i5",
    processorGeneration: "11th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "13 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 370000,
  },
  {
    id: 15,
    images: ["/images/elitebook-1030-G2.png", "/images/elitebook-1030-G2-2.png"],
    brand: "HP",
    model: "Elitebook 1030 G2",
    processor: "Intel Core i7",
    processorGeneration: "7th Gen",
    ram: "16GB",
    storage: "512GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "Yes, X360",
    keyboardLight: "Yes",
    price: 480000,
  },
  {
    id: 16,
    images: ["/images/latitude5570.png", "/images/latitude5570_1.png"],
    brand: "DELL",
    model: "Latitude 5570",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15.6 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 17,
    images: ["/images/latitude3567.png", "/images/latitude3567_1.png"],
    brand: "DELL",
    model: "inspiron 15 3567",
    processor: "Intel Core i3",
    processorGeneration: "7th Gen",
    ram: "8GB",
    storage: "180GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "15.6 inches",
    touchscreen: "Yes",
    keyboardLight: "Yes",
    price: 220000,
  },
  {
    id: 18,
    images: ["/images/latitude7270.png", "/images/latitude7270_1.png"],
    brand: "DELL",
    model: "Latitude 7270",
    processor: "Intel Core i5",
    processorGeneration: "6th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "12.5 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
]