
export type Product = {
  id: number
  images: string[]
  brand: string
  model: string
  price: number
  processorGeneration: string
  processor: string
  ram: string
  storage: string
  batteryHealth: string
  webcam: string
  bluetooth: string
  screenSize: string
  touchscreen: string
  keyboardLight: string
}

export const products: Product[] = [
  {
    id: 1,
    images: ["/images/HP-840-G3.png", "/images/hp-zbook-14u.png", "/images/Hp-probook-440-G7.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 2,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 3,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 4,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 5,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 6,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 7,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 8,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 9,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 10,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 11,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 12,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 13,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 14,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 15,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 16,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 17,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
  {
    id: 18,
    images: ["/images/HP-840-G3.png", "/images/HP-840-G3.png", "/images/HP-840-G3.png"],
    brand: "HP",
    model: "EliteBook 840 G3",
    processor: "Intel Core i5",
    processorGeneration: "8th Gen",
    ram: "8GB",
    storage: "256GB SSD",
    batteryHealth: "Excellent",
    webcam: "Yes",
    bluetooth: "Yes",
    screenSize: "14 inches",
    touchscreen: "No",
    keyboardLight: "Yes",
    price: 260000,
  },
]